#!/usr/bin/env zsh

Black="\033[30m"
R="\033[31m"
G="\033[32m"
Y="\033[33m"
B="\033[34m"
P="\033[35m"
C="\033[36m"
W="\033[37m"
BR="\033[101m"
BG="\033[102m"
BY="\033[103m"
BB="\033[104m"
BP="\033[105m"
BC="\033[106m"
BW="\033[107m"
Alt="\xef\xac\xb4"
Cmd="\xef\xac\xb2"
Arrow="$B \xef\xa8\xaf $C"
List="\xef\x9d\xba"
Or="$B \xee\x83\x8f$C  "
Id="\xef\xaf\xa6"
old="$W"old"$C"
new="$W"new"$C"

echo "\n"
echo "$Y	$List Navigation:"

echo "$G open file manager 			$Arrow Ctrl + O"
echo "$G move word left/right 			$Arrow $Alt + Left/Right" 
echo "$G cut previous word 			$Arrow Ctrl + W"
echo "$G front of line	 			$Arrow Ctrl + A"
echo "$G back (End) of line 			$Arrow Ctrl + E"
echo "$G cut before cursor 			$Arrow Ctrl + U"
echo "$G cut after cursor (Kill) 		$Arrow Ctrl + K"
echo "$G paste cut selection (Yank) 		$Arrow Ctrl + Y"
echo "$G swap last 2 words 			$Arrow Esc + T"
echo "$G insert last word from previous command $Arrow Esc + ."
echo "$G prepend last command with sudo         $Arrow Esc Esc"
echo "$G park a command 			$Arrow Ctrl + q"

echo "\n$Y 	$List Commands:"

echo "$P search history				$Arrow Ctrl + R"
echo "$P last$W n$P commands			$Arrow h$W -n"
echo "$P last command				$Arrow !!"
echo "$P replace once in last command		$Arrow !!:s/$old/$new/ $Or ^$old^$new"
echo "$P replace global in last command		$Arrow !!:gs/$old/$new/"
echo "$P replace global & run last command	$Arrow r $old=$new"
echo "$P last command starting with		$Arrow !$W\[start letters\]$Y$Id :gs/$old$Y/$new"
echo "$P repeat$W n$P-th last command		$Arrow !$W-n"
echo "$P insert all arguments from last command	$Arrow !* 	(everything but 1st token)"
echo "$P insert last word from last command	$Arrow !$"
echo "$P insert$W n$P-th word from last cmd		$Arrow !:$W"n" $Or !:$W"from"$C-$W"to" $Or !:$W"from"$C-\$ (till end)"
echo "$P clear screen				$Arrow clear $Or $Cmd  + K"
echo "$P list all aliases			$Arrow alias"
echo "$P one dir up                             $Arrow .. $Y$Id ...$W two up, $Y....$W three up etc.."
echo "$P back to previous directory		$Arrow cd - $Or - $Or 1"
echo "$P back to$W n$P-th previous dir              $Arrow n"
echo "$P list last dirs                         $Arrow d"
echo "$P find in tree				$Arrow find . | grep$W name$C (slow) $Or locate$W name$C (faster)"
echo "$P recursively glob subdirs		$Arrow **/*$W"search-string""
echo "$P recursively glob indlude dotfiles/dirs	$Arrow **/*$W"search-string"$C(D)"
echo "$P make dir & cd in it                    $Arrow take"
echo "$P batch create with several strings      $Arrow touch test{1,2,'icle'}.txt"
echo "$P batch create with range                $Arrow mkdir test{1..10}"

echo "\n$P display processes 			$Arrow top $Or sudo htop $Or ps -A $Or pgrep"
echo "$P kill processes				$Arrow pkill$W name $Or killall$W name"

echo "$P install plugin with antigen            $Arrow antigen bundle$W plugin name"
echo "\n$P curl with redirect 			$Arrow -o$W filename $P-L$W URL"
echo "$P ssh copy				$Arrow scp$W username$C@$W"host"-name$C.local:'$W/path/to/file$C' $W/local/path"
echo "$Y						$Id For host name use $W-$Y for spaces, for filenames use different quotes"
echo "$P cut display after delimiter		$Arrow cut -d\" \" -f2 "
echo "$P make columns				$Arrow column -t -s \"$W"delimiter"$C\""
echo "$P stream editor				$Arrow sed \"s/$old/$new/g\""
echo "$Y	$Id change in multiple files	$Arrow   $Y$Id$C for f in$W query$C*; do"
echo "						 sed -i \"s/$W"old"$C/$W"new"$C/g\" $f"
echo "						 done"
echo "$P grep with awk				$Arrow awk '/$W"pattern"$C/'"
echo "$P print selection between queries	$Arrow awk '/$W"fromPattern"$C/,/$W"tillPattern"$C/'"
echo "$P replace with awk			$Arrow awk '{sub(/$W"pattern"$C/,\"$W"new"$C\")}1'  $Y$Id gsub = global"
echo "$P find intersection of files		$Arrow awk 'NR==FNR{a[\$0];next} \$0 in a'$W file1 file2"
echo "$P awk 2 files different conditions	$Arrow awk 'NR==FNR {$W  some actions$C; next}$W condition$C {$W other actions$C}'$W file1 file2"
echo "						$Y$Id NR==NFR true voor 1e file"
echo "$P find console encoding for unicode char $Arrow echo '\Uf779' | hexdump"
echo "$P download files in range   	        $Arrow wget -L https://$W"url$C"/{$W"start"$C..$W"end"$C}.png"
echo "$P print missing files in range   	$Arrow for x in {$W"start"$C..$W"end"$C}; if [[ ! -s \$x'.png' ]] echo \$x"
echo "$P batch rename files                	$Arrow zmv '$W"input_pattern"$C' '$W"output_pattern"$C'"
echo "						$Y$Id $C"zmv \'$W"lucif e-(*)"$C\' \'$W"Lucifer ep-\$1$C'" 
echo "$P rename using sequential numbering      $Arrow count=1; zmv '$W(*)_*.jpg$C' '\$1-\$((count++)).jpg'"
echo "						$Y$Id -n for dry-run , -C for Copy, \${1$C:l$Y} for variable to lower case"

echo "\n$Y 	$List User Aliases:$C"
echo "$G"tree"$W n  $Arrow  show dir tree depth$W n$G (default = 2) "
echo "$G"gtop"   $Arrow  go to top dir of github repo"
command grep "alias .*='.*" ~/.useraliases | cut -d" " -f2- | column -t -s "'" 
